services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      # базовые настройки
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_ENCRYPTION_KEY
        value: "matrix2025key"
      - key: GENERIC_TIMEZONE
        value: "Europe/Moscow"
      - key: N8N_SECURE_COOKIE
        value: "false"

      # укажи тип БД и доступы (замени на свои)
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "<HOST>"
      - key: DB_POSTGRESDB_DATABASE
        value: "<DATABASE>"
      - key: DB_POSTGRESDB_USER
        value: "<USER>"
      - key: DB_POSTGRESDB_PASSWORD
        value: "<PASSWORD>"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
