services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: frankfurt

    envVars:
      # Основные настройки n8n
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_ENCRYPTION_KEY
        value: "E4uid010101"
      - key: GENERIC_TIMEZONE
        value: "Europe/Moscow"
      - key: N8N_SECURE_COOKIE
        value: "false"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

      # Подключение PostgreSQL
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "dpg-d3omnuk9c44c738av660-a"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "n8n_postgres_bq5x"
      - key: DB_POSTGRESDB_USER
        value: "n8n_postgres_bq5x_user"
      - key: DB_POSTGRESDB_PASSWORD
        value: "ZeiC7XBvR4m6QtTz21KXOi9MPDxUFbEDh"

      # Авторизация в веб-интерфейсе n8n
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "matrix2025"
