services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      # --- Основные настройки n8n ---
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_ENCRYPTION_KEY
        value: E4uid010101
      - key: GENERIC_TIMEZONE
        value: Europe/Moscow
      - key: N8N_SECURE_COOKIE
        value: "false"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
      - key: WEBHOOK_URL
        value: https://n8n-render-30ic.onrender.com/
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-render-30ic.onrender.com/
      
      # --- Подключение PostgreSQL ---
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_CONNECTION_URL
        # 👇 ВСТАВЬ СВОЙ ПОЛНЫЙ EXTERNAL DATABASE URL сюда!
        value: postgres://n8n_postgres_bq5x_user:ZeiC7XRv4m6...@dpg-d3omnu...frankfurt-postgres.render.com/n8n_postgres_bq5x

      # --- Права и стабильность ---
      - key: N8N_RELEASE_TYPE
        value: stable
      - key: NODE_ENV
        value: production
