services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_ENCRYPTION_KEY
        value: E4uid010101
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: GENERIC_TIMEZONE
        value: Europe/Moscow
      - key: NODE_ENV
        value: production
      - key: DB_TYPE
        value: postgresdb
      # 👇 Render сам подставит URL из базы, когда добавим link
      - key: DB_POSTGRESDB_CONNECTION_URL
        fromDatabase:
          name: n8n-db
          property: connectionString
      - key: WEBHOOK_URL
        value: https://n8n-render.onrender.com/
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-render.onrender.com/

databases:
  - name: n8n-db
    databaseName: n8n
    user: n8n_user
